[
  "peppered snail",
  "moi moi",
  "efo riro (vegetable soup)",
  "gizzard stir",
  "yam porridge",
  "moi moi",
  "efo riro (vegetable soup)",
  "gizzard stir",
  "yam porridge",
  "moi moi",
  "efo riro (vegetable soup)",
  "gizzard stir",
  "yam porridge",
  "ofe akwu (banga soup with palm fruit) with chicken",
  "efo riro (vegetable soup)",
  "gizzard stir",
  "yam porridge",
  "ofe akwu (banga soup with palm fruit) with chicken",
  "efo riro (vegetable soup)",
  "gizzard stir",
  "yam porridge",
  "ofe akwu (banga soup with palm fruit) with chicken",
  "efo riro (vegetable soup)",
  "gizzard stir",
  "yam porridge",
  "ofe akwu (banga soup with palm fruit) with chicken",
  "ofe nsala (white soup) with fish",
  "efo riro (vegetable soup)",
  "gizzard stir",
  "yam porridge",
  "ofe akwu (banga soup with palm fruit) with chicken",
  "ofe nsala (white soup) with fish",
  "gizzard stir",
  "yam porridge",
  "ofe akwu (banga soup with palm fruit) with chicken",
  "ofe nsala (white soup) with fish",
  "gizzard stir",
  "yam porridge",
  "ofe akwu (banga soup with palm fruit) with chicken",
  "ofe nsala (white soup) with fish",
  "gizzard stir",
  "yam porridge",
  "ofe akwu (banga soup with palm fruit) with chicken",
  "ofe nsala (white soup) with fish",
  "chicken and veggie kebabs",
  "gizzard stir",
  "yam porridge",
  "ofe akwu (banga soup with palm fruit) with chicken",
  "ofe nsala (white soup) with fish",
  "chicken and veggie kebabs",
];
